# Generated by Django 6.0.6 on 2026-07-08 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_books_options_borrowedbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowedbook',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='my_constraint'),
        ),
    ]
