# Generated by Django 6.0.6 on 2026-07-24 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_borrowedbook_my_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='fee',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='no_of_books',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
