# Generated by Django 6.0.6 on 2026-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_borrowedbook_fee_borrowedbook_no_of_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
