# Generated by Django 6.0.6 on 2026-07-28 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_borrowedbook_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='no_of_books',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
