# Generated by Django 6.0.6 on 2026-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_borrowedbook_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
