# Generated by Django 6.0.6 on 2026-09-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_borrowedbook_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
