# Generated by Django 6.0.6 on 2026-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_borrowedbookrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
