# Generated by Django 6.0.6 on 2026-09-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_borrowedbook_is_returned'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowedbook',
            name='my_constraint',
        ),
    ]
